-- تصنيف المهن والوظائف
UPDATE words SET category = 'professions' WHERE word_en IN ('doctor', 'nurse', 'engineer', 'lawyer', 'architect', 'dentist', 'pilot', 'chef', 'waiter', 'waitress', 'driver', 'farmer', 'scientist', 'artist', 'musician', 'singer', 'dancer', 'writer', 'author', 'journalist', 'reporter', 'photographer', 'designer', 'programmer', 'developer', 'accountant', 'banker', 'mechanic', 'electrician', 'plumber', 'carpenter', 'painter', 'police', 'policeman', 'policewoman', 'firefighter', 'soldier', 'actor', 'actress', 'director', 'producer', 'coach', 'athlete', 'player', 'secretary', 'receptionist', 'clerk', 'cashier', 'salesperson', 'consultant', 'analyst', 'researcher', 'professor', 'lecturer', 'instructor', 'tutor', 'counselor', 'therapist', 'psychologist', 'psychiatrist', 'surgeon', 'pharmacist', 'veterinarian', 'vet') AND category LIKE 'general%';

-- تصنيف الرياضة
UPDATE words SET category = 'sports' WHERE word_en IN ('sport', 'sports', 'game', 'play', 'team', 'match', 'competition', 'tournament', 'championship', 'race', 'win', 'lose', 'draw', 'score', 'goal', 'point', 'points', 'ball', 'football', 'soccer', 'basketball', 'tennis', 'volleyball', 'swimming', 'running', 'cycling', 'golf', 'boxing', 'wrestling', 'martial arts', 'gym', 'exercise', 'training', 'practice', 'fitness', 'workout', 'stretch', 'warm up', 'champion', 'winner', 'loser', 'player', 'athlete', 'coach', 'referee', 'stadium', 'field', 'court', 'pool', 'track') AND category LIKE 'general%';

-- تصنيف الصحة والطب
UPDATE words SET category = 'health' WHERE word_en IN ('health', 'healthy', 'unhealthy', 'sick', 'ill', 'illness', 'disease', 'virus', 'infection', 'fever', 'cold', 'flu', 'cough', 'headache', 'pain', 'ache', 'hurt', 'injury', 'wound', 'bleeding', 'medicine', 'medication', 'drug', 'pill', 'tablet', 'injection', 'vaccine', 'treatment', 'therapy', 'surgery', 'operation', 'hospital', 'clinic', 'pharmacy', 'doctor', 'patient', 'nurse', 'symptom', 'diagnosis', 'cure', 'recover', 'recovery', 'heal', 'healing', 'diet', 'nutrition', 'vitamin', 'allergy', 'allergic', 'asthma', 'diabetes', 'cancer', 'heart attack', 'stroke', 'blood pressure', 'temperature', 'check-up', 'appointment', 'prescription', 'emergency', 'ambulance', 'wheelchair', 'bandage', 'cast') AND category LIKE 'general%';

-- تصنيف التكنولوجيا والإنترنت
UPDATE words SET category = 'technology' WHERE word_en IN ('technology', 'computer', 'laptop', 'tablet', 'phone', 'smartphone', 'mobile', 'device', 'screen', 'keyboard', 'mouse', 'monitor', 'printer', 'scanner', 'camera', 'internet', 'website', 'web', 'online', 'offline', 'download', 'upload', 'click', 'tap', 'swipe', 'scroll', 'search', 'browse', 'surf', 'email', 'message', 'text', 'chat', 'video', 'audio', 'image', 'file', 'folder', 'document', 'software', 'hardware', 'app', 'application', 'program', 'system', 'network', 'wifi', 'connection', 'password', 'username', 'account', 'login', 'logout', 'register', 'sign up', 'sign in', 'data', 'database', 'server', 'cloud', 'storage', 'backup', 'update', 'upgrade', 'install', 'uninstall', 'delete', 'copy', 'paste', 'cut', 'save', 'share', 'post', 'like', 'comment', 'follow', 'subscribe', 'notification', 'alert', 'setting', 'settings', 'privacy', 'security', 'virus', 'hack', 'hacker', 'digital', 'virtual', 'artificial intelligence', 'AI', 'robot', 'automation') AND category LIKE 'general%';

-- تصنيف الطبيعة والبيئة
UPDATE words SET category = 'nature' WHERE word_en IN ('nature', 'natural', 'environment', 'environmental', 'earth', 'world', 'planet', 'sun', 'moon', 'star', 'stars', 'sky', 'space', 'universe', 'air', 'water', 'fire', 'land', 'ground', 'soil', 'rock', 'stone', 'sand', 'dust', 'mud', 'tree', 'plant', 'flower', 'grass', 'leaf', 'leaves', 'branch', 'root', 'seed', 'forest', 'jungle', 'garden', 'park', 'mountain', 'hill', 'valley', 'river', 'stream', 'lake', 'pond', 'ocean', 'sea', 'beach', 'shore', 'coast', 'island', 'desert', 'cave', 'waterfall', 'volcano', 'earthquake', 'flood', 'drought', 'pollution', 'climate', 'global warming', 'recycle', 'renewable', 'sustainable', 'organic', 'wildlife', 'habitat', 'ecosystem', 'species', 'endangered', 'extinct', 'conservation') AND category LIKE 'general%';

-- تصنيف الحيوانات
UPDATE words SET category = 'animals' WHERE word_en IN ('animal', 'animals', 'pet', 'pets', 'dog', 'cat', 'bird', 'fish', 'horse', 'cow', 'pig', 'sheep', 'goat', 'chicken', 'duck', 'rabbit', 'mouse', 'rat', 'elephant', 'lion', 'tiger', 'bear', 'monkey', 'snake', 'crocodile', 'alligator', 'turtle', 'frog', 'whale', 'dolphin', 'shark', 'octopus', 'spider', 'insect', 'bee', 'butterfly', 'ant', 'fly', 'mosquito', 'wolf', 'fox', 'deer', 'giraffe', 'zebra', 'kangaroo', 'penguin', 'eagle', 'owl', 'parrot', 'dinosaur', 'pet', 'wild', 'domestic', 'cage', 'zoo', 'aquarium', 'farm', 'barn', 'nest', 'wing', 'tail', 'paw', 'claw', 'fur', 'feather', 'scale') AND category LIKE 'general%';

-- تصنيف المنزل والأثاث
UPDATE words SET category = 'home' WHERE word_en IN ('home', 'house', 'apartment', 'flat', 'building', 'room', 'bedroom', 'bathroom', 'kitchen', 'living room', 'dining room', 'garage', 'balcony', 'terrace', 'roof', 'ceiling', 'floor', 'wall', 'door', 'window', 'stairs', 'elevator', 'lift', 'furniture', 'bed', 'sofa', 'couch', 'chair', 'table', 'desk', 'shelf', 'shelves', 'cabinet', 'drawer', 'closet', 'wardrobe', 'mirror', 'lamp', 'light', 'fan', 'air conditioner', 'heater', 'refrigerator', 'fridge', 'freezer', 'oven', 'stove', 'microwave', 'dishwasher', 'washing machine', 'dryer', 'iron', 'vacuum', 'broom', 'mop', 'bucket', 'towel', 'blanket', 'pillow', 'sheet', 'curtain', 'carpet', 'rug', 'sink', 'toilet', 'shower', 'bathtub', 'tap', 'faucet', 'key', 'lock', 'rent', 'landlord', 'tenant', 'neighbor', 'neighborhood', 'address', 'move', 'moving', 'decorate', 'decoration', 'clean', 'cleaning', 'tidy', 'mess', 'messy') AND category LIKE 'general%';

-- تصنيف المال والأعمال
UPDATE words SET category = 'money' WHERE word_en IN ('money', 'cash', 'coin', 'coins', 'note', 'notes', 'bill', 'bills', 'currency', 'dollar', 'euro', 'pound', 'cent', 'price', 'cost', 'expensive', 'cheap', 'free', 'afford', 'pay', 'payment', 'buy', 'purchase', 'sell', 'sale', 'discount', 'offer', 'deal', 'bargain', 'spend', 'save', 'savings', 'invest', 'investment', 'profit', 'loss', 'income', 'salary', 'wage', 'bonus', 'tax', 'taxes', 'debt', 'loan', 'borrow', 'lend', 'owe', 'bank', 'account', 'deposit', 'withdraw', 'withdrawal', 'transfer', 'transaction', 'balance', 'credit', 'debit', 'card', 'credit card', 'debit card', 'ATM', 'cash machine', 'receipt', 'invoice', 'budget', 'economy', 'economic', 'financial', 'finance', 'insurance', 'stock', 'stocks', 'share', 'shares', 'market', 'trade', 'trading', 'exchange', 'rate', 'interest', 'mortgage', 'rent', 'fee', 'charge', 'tip', 'donation', 'charity', 'wealth', 'wealthy', 'rich', 'poor', 'poverty', 'bankrupt', 'bankruptcy') AND category LIKE 'general%';

-- تصنيف الاتجاهات والمواقع
UPDATE words SET category = 'directions' WHERE word_en IN ('direction', 'directions', 'left', 'right', 'up', 'down', 'forward', 'backward', 'backwards', 'straight', 'north', 'south', 'east', 'west', 'northeast', 'northwest', 'southeast', 'southwest', 'center', 'centre', 'middle', 'side', 'corner', 'edge', 'top', 'bottom', 'front', 'back', 'inside', 'outside', 'here', 'there', 'where', 'everywhere', 'somewhere', 'nowhere', 'anywhere', 'near', 'far', 'close', 'distant', 'distance', 'location', 'position', 'place', 'area', 'region', 'zone', 'border', 'boundary', 'map', 'compass', 'GPS', 'navigate', 'navigation', 'route', 'path', 'way', 'road', 'street', 'avenue', 'highway', 'intersection', 'crossroad', 'turn', 'cross', 'pass', 'entrance', 'exit', 'arrival', 'departure', 'destination') AND category LIKE 'general%';

-- تصنيف الترفيه والفنون
UPDATE words SET category = 'entertainment' WHERE word_en IN ('entertainment', 'fun', 'enjoy', 'enjoyment', 'pleasure', 'hobby', 'hobbies', 'game', 'games', 'toy', 'toys', 'play', 'playing', 'movie', 'film', 'cinema', 'theater', 'theatre', 'show', 'concert', 'performance', 'perform', 'act', 'acting', 'drama', 'comedy', 'tragedy', 'horror', 'action', 'romance', 'documentary', 'series', 'episode', 'season', 'channel', 'broadcast', 'TV', 'television', 'radio', 'music', 'song', 'sing', 'singer', 'band', 'orchestra', 'instrument', 'guitar', 'piano', 'violin', 'drum', 'drums', 'dance', 'dancing', 'dancer', 'art', 'artist', 'paint', 'painting', 'draw', 'drawing', 'sketch', 'sculpture', 'museum', 'gallery', 'exhibition', 'photography', 'photograph', 'photo', 'picture', 'image', 'video', 'animation', 'cartoon', 'comic', 'book', 'novel', 'story', 'poem', 'poetry', 'literature', 'read', 'reading', 'write', 'writing', 'author', 'character', 'plot', 'scene', 'setting', 'theme', 'fiction', 'non-fiction', 'fantasy', 'science fiction', 'mystery', 'thriller', 'adventure', 'biography', 'autobiography', 'history', 'historical', 'party', 'celebration', 'celebrate', 'festival', 'holiday', 'vacation', 'trip', 'travel', 'tourist', 'tourism', 'sightseeing', 'attraction', 'amusement park', 'theme park', 'zoo', 'aquarium', 'circus', 'magic', 'magician', 'trick', 'puzzle', 'riddle', 'joke', 'funny', 'laugh', 'laughter', 'smile', 'clown') AND category LIKE 'general%';

-- تصنيف الاتصالات والتواصل
UPDATE words SET category = 'communication' WHERE word_en IN ('communication', 'communicate', 'speak', 'speech', 'talk', 'conversation', 'discuss', 'discussion', 'debate', 'argue', 'argument', 'agree', 'agreement', 'disagree', 'disagreement', 'opinion', 'view', 'point of view', 'perspective', 'idea', 'thought', 'think', 'believe', 'belief', 'suggest', 'suggestion', 'recommend', 'recommendation', 'advise', 'advice', 'warn', 'warning', 'inform', 'information', 'news', 'announce', 'announcement', 'declare', 'declaration', 'statement', 'claim', 'explain', 'explanation', 'describe', 'description', 'express', 'expression', 'mean', 'meaning', 'definition', 'define', 'clarify', 'confirm', 'deny', 'admit', 'confess', 'apologize', 'apology', 'forgive', 'forgiveness', 'thank', 'thanks', 'gratitude', 'compliment', 'complain', 'complaint', 'criticize', 'criticism', 'praise', 'encourage', 'encouragement', 'motivate', 'motivation', 'inspire', 'inspiration', 'persuade', 'convince', 'negotiate', 'negotiation', 'compromise', 'promise', 'swear', 'oath', 'secret', 'whisper', 'shout', 'yell', 'scream', 'cry', 'mumble', 'stutter', 'pause', 'silence', 'silent', 'quiet', 'loud', 'noise', 'noisy', 'sound', 'voice', 'tone', 'accent', 'pronunciation', 'pronounce', 'spell', 'spelling', 'grammar', 'vocabulary', 'word', 'sentence', 'paragraph', 'text', 'message', 'letter', 'email', 'mail', 'phone', 'call', 'ring', 'answer', 'hang up', 'voicemail', 'contact', 'reach', 'respond', 'response', 'reply', 'feedback') AND category LIKE 'general%';

-- تصنيف القانون والعدالة
UPDATE words SET category = 'law' WHERE word_en IN ('law', 'legal', 'illegal', 'crime', 'criminal', 'police', 'arrest', 'prison', 'jail', 'prisoner', 'court', 'judge', 'jury', 'lawyer', 'attorney', 'trial', 'case', 'evidence', 'witness', 'testimony', 'verdict', 'guilty', 'innocent', 'sentence', 'punishment', 'fine', 'penalty', 'parole', 'bail', 'sue', 'lawsuit', 'claim', 'defend', 'defense', 'prosecute', 'prosecutor', 'accuse', 'accusation', 'charge', 'convict', 'conviction', 'appeal', 'justice', 'injustice', 'fair', 'unfair', 'right', 'rights', 'human rights', 'civil rights', 'constitution', 'amendment', 'regulation', 'rule', 'rules', 'policy', 'permit', 'permission', 'license', 'ban', 'prohibit', 'forbidden', 'allow', 'allowed', 'legal', 'illegal', 'crime', 'theft', 'steal', 'rob', 'robbery', 'burglary', 'fraud', 'murder', 'assault', 'abuse', 'harassment', 'discrimination', 'corruption', 'bribe', 'smuggle', 'smuggling', 'drug', 'drugs', 'trafficking', 'kidnap', 'kidnapping', 'terrorist', 'terrorism', 'investigation', 'investigate', 'detective', 'suspect', 'victim') AND category LIKE 'general%';

-- تصنيف الحكومة والسياسة
UPDATE words SET category = 'politics' WHERE word_en IN ('politics', 'political', 'politician', 'government', 'govern', 'state', 'nation', 'national', 'international', 'country', 'countries', 'citizen', 'citizenship', 'nationality', 'passport', 'visa', 'immigrant', 'immigration', 'emigrate', 'emigration', 'refugee', 'asylum', 'border', 'customs', 'president', 'prime minister', 'minister', 'king', 'queen', 'prince', 'princess', 'royal', 'monarchy', 'republic', 'democracy', 'democratic', 'dictatorship', 'dictator', 'communism', 'communist', 'socialism', 'socialist', 'capitalism', 'capitalist', 'liberal', 'conservative', 'party', 'election', 'vote', 'voter', 'voting', 'campaign', 'candidate', 'ballot', 'poll', 'parliament', 'congress', 'senate', 'senator', 'representative', 'legislation', 'legislate', 'bill', 'act', 'law', 'policy', 'reform', 'revolution', 'rebel', 'rebellion', 'protest', 'demonstrate', 'demonstration', 'march', 'rally', 'strike', 'union', 'treaty', 'agreement', 'alliance', 'war', 'peace', 'conflict', 'negotiate', 'diplomacy', 'diplomat', 'embassy', 'ambassador', 'foreign', 'domestic', 'military', 'army', 'navy', 'air force', 'soldier', 'troops', 'weapon', 'weapons', 'nuclear', 'missile', 'bomb', 'attack', 'defend', 'defense', 'security', 'intelligence', 'spy', 'espionage') AND category LIKE 'general%';

-- تصنيف الدين والروحانية
UPDATE words SET category = 'religion' WHERE word_en IN ('religion', 'religious', 'faith', 'believe', 'belief', 'god', 'gods', 'goddess', 'divine', 'holy', 'sacred', 'spiritual', 'spirituality', 'soul', 'spirit', 'heaven', 'hell', 'angel', 'devil', 'demon', 'miracle', 'pray', 'prayer', 'worship', 'church', 'mosque', 'temple', 'synagogue', 'cathedral', 'chapel', 'shrine', 'priest', 'pastor', 'minister', 'imam', 'rabbi', 'monk', 'nun', 'prophet', 'saint', 'blessing', 'bless', 'curse', 'sin', 'sinful', 'forgive', 'forgiveness', 'salvation', 'redeem', 'redemption', 'ritual', 'ceremony', 'tradition', 'custom', 'scripture', 'bible', 'quran', 'torah', 'gospel', 'verse', 'chapter', 'commandment', 'sermon', 'preach', 'convert', 'conversion', 'baptism', 'baptize', 'communion', 'confession', 'meditation', 'meditate', 'enlightenment', 'karma', 'reincarnation', 'afterlife', 'resurrection', 'crucifixion', 'pilgrimage', 'fast', 'fasting', 'charity', 'alms', 'tithe', 'offering', 'sacrifice', 'christian', 'christianity', 'muslim', 'islam', 'jewish', 'judaism', 'hindu', 'hinduism', 'buddhist', 'buddhism', 'atheist', 'atheism', 'agnostic') AND category LIKE 'general%';

-- تصنيف العلوم
UPDATE words SET category = 'science' WHERE word_en IN ('science', 'scientific', 'scientist', 'research', 'researcher', 'study', 'experiment', 'laboratory', 'lab', 'test', 'theory', 'hypothesis', 'prove', 'proof', 'evidence', 'data', 'analysis', 'analyze', 'result', 'results', 'conclusion', 'discover', 'discovery', 'invent', 'invention', 'inventor', 'technology', 'physics', 'chemistry', 'biology', 'mathematics', 'math', 'maths', 'geometry', 'algebra', 'calculus', 'statistics', 'formula', 'equation', 'calculate', 'calculation', 'measure', 'measurement', 'unit', 'meter', 'kilogram', 'liter', 'celsius', 'fahrenheit', 'atom', 'molecule', 'element', 'compound', 'chemical', 'reaction', 'energy', 'force', 'power', 'electricity', 'electric', 'magnetic', 'magnetism', 'gravity', 'mass', 'weight', 'volume', 'density', 'pressure', 'temperature', 'heat', 'light', 'sound', 'wave', 'frequency', 'radiation', 'nuclear', 'particle', 'cell', 'DNA', 'gene', 'genetic', 'chromosome', 'organism', 'species', 'evolution', 'evolve', 'adapt', 'adaptation', 'fossil', 'dinosaur', 'extinct', 'extinction', 'microscope', 'telescope', 'lens', 'spectrum', 'bacteria', 'virus', 'vaccine', 'antibiotic', 'infection') AND category LIKE 'general%';

-- تصنيف الصفات السلبية
UPDATE words SET category = 'adjectives_negative' WHERE word_en IN ('bad', 'terrible', 'horrible', 'awful', 'dreadful', 'disgusting', 'nasty', 'unpleasant', 'annoying', 'irritating', 'boring', 'dull', 'stupid', 'foolish', 'silly', 'crazy', 'insane', 'mad', 'angry', 'furious', 'upset', 'disappointed', 'frustrated', 'depressed', 'miserable', 'unhappy', 'sad', 'gloomy', 'pessimistic', 'negative', 'critical', 'harsh', 'cruel', 'mean', 'rude', 'impolite', 'disrespectful', 'selfish', 'greedy', 'jealous', 'envious', 'arrogant', 'proud', 'vain', 'stubborn', 'lazy', 'careless', 'irresponsible', 'unreliable', 'dishonest', 'unfair', 'unjust', 'corrupt', 'evil', 'wicked', 'violent', 'aggressive', 'hostile', 'dangerous', 'risky', 'harmful', 'toxic', 'poisonous', 'deadly', 'fatal', 'weak', 'fragile', 'vulnerable', 'helpless', 'hopeless', 'useless', 'worthless', 'meaningless', 'pointless', 'ridiculous', 'absurd', 'impossible', 'unbelievable', 'incredible', 'shocking', 'outrageous', 'unacceptable', 'intolerable', 'unbearable') AND category LIKE 'general%';

-- تصنيف الصفات الإيجابية
UPDATE words SET category = 'adjectives_positive' WHERE word_en IN ('good', 'great', 'excellent', 'amazing', 'wonderful', 'fantastic', 'incredible', 'awesome', 'brilliant', 'outstanding', 'exceptional', 'remarkable', 'impressive', 'magnificent', 'superb', 'splendid', 'lovely', 'beautiful', 'gorgeous', 'stunning', 'attractive', 'charming', 'elegant', 'graceful', 'pleasant', 'enjoyable', 'delightful', 'satisfying', 'fulfilling', 'rewarding', 'successful', 'prosperous', 'fortunate', 'lucky', 'blessed', 'grateful', 'thankful', 'appreciative', 'happy', 'joyful', 'cheerful', 'optimistic', 'positive', 'enthusiastic', 'excited', 'passionate', 'motivated', 'inspired', 'creative', 'innovative', 'original', 'unique', 'special', 'precious', 'valuable', 'worthy', 'meaningful', 'significant', 'important', 'essential', 'necessary', 'useful', 'helpful', 'beneficial', 'advantageous', 'convenient', 'comfortable', 'cozy', 'relaxing', 'peaceful', 'calm', 'quiet', 'gentle', 'kind', 'friendly', 'warm', 'welcoming', 'hospitable', 'generous', 'caring', 'loving', 'supportive', 'encouraging', 'understanding', 'patient', 'tolerant', 'respectful', 'polite', 'courteous', 'honest', 'sincere', 'genuine', 'authentic', 'reliable', 'trustworthy', 'responsible', 'dedicated', 'committed', 'determined', 'ambitious', 'hardworking', 'diligent', 'efficient', 'organized', 'neat', 'clean', 'tidy', 'smart', 'intelligent', 'clever', 'wise', 'knowledgeable', 'experienced', 'skilled', 'talented', 'gifted', 'capable', 'competent', 'qualified', 'professional', 'mature', 'sensible', 'reasonable', 'practical', 'realistic', 'logical', 'rational', 'fair', 'just', 'balanced', 'moderate', 'flexible', 'adaptable', 'open-minded', 'curious', 'interested', 'engaged', 'active', 'energetic', 'dynamic', 'lively', 'vibrant', 'fresh', 'new', 'modern', 'advanced', 'innovative', 'progressive', 'forward-thinking') AND category LIKE 'general%';

-- تصنيف الأفعال المساعدة والنمطية
UPDATE words SET category = 'modal_verbs' WHERE word_en IN ('can', 'could', 'may', 'might', 'will', 'would', 'shall', 'should', 'must', 'ought', 'need', 'dare', 'used to', 'had better', 'would rather') AND category LIKE 'general%';

-- تصنيف الظروف
UPDATE words SET category = 'adverbs' WHERE word_en IN ('very', 'really', 'quite', 'rather', 'fairly', 'pretty', 'extremely', 'incredibly', 'absolutely', 'completely', 'totally', 'entirely', 'fully', 'partly', 'partially', 'almost', 'nearly', 'hardly', 'barely', 'scarcely', 'just', 'only', 'even', 'still', 'already', 'yet', 'always', 'never', 'ever', 'often', 'usually', 'sometimes', 'occasionally', 'rarely', 'seldom', 'frequently', 'constantly', 'continuously', 'regularly', 'normally', 'generally', 'typically', 'mainly', 'mostly', 'largely', 'primarily', 'basically', 'essentially', 'fundamentally', 'obviously', 'clearly', 'apparently', 'evidently', 'certainly', 'definitely', 'surely', 'probably', 'possibly', 'perhaps', 'maybe', 'likely', 'unlikely', 'fortunately', 'unfortunately', 'luckily', 'unluckily', 'hopefully', 'surprisingly', 'interestingly', 'importantly', 'significantly', 'consequently', 'therefore', 'thus', 'hence', 'accordingly', 'however', 'nevertheless', 'nonetheless', 'otherwise', 'instead', 'moreover', 'furthermore', 'besides', 'also', 'too', 'as well', 'either', 'neither', 'anyway', 'anyhow', 'somehow', 'somewhere', 'anywhere', 'everywhere', 'nowhere', 'here', 'there', 'now', 'then', 'today', 'yesterday', 'tomorrow', 'soon', 'later', 'immediately', 'instantly', 'suddenly', 'gradually', 'slowly', 'quickly', 'fast', 'rapidly', 'promptly', 'eventually', 'finally', 'lastly', 'firstly', 'secondly', 'next', 'afterwards', 'meanwhile', 'beforehand', 'well', 'badly', 'carefully', 'carelessly', 'easily', 'simply', 'freely', 'safely', 'seriously', 'honestly', 'truly', 'genuinely', 'perfectly', 'properly', 'correctly', 'accurately', 'precisely', 'exactly', 'approximately', 'roughly', 'together', 'separately', 'alone', 'apart', 'aside', 'away', 'back', 'forward', 'upward', 'downward', 'inward', 'outward', 'across', 'along', 'around', 'through', 'throughout', 'over', 'under', 'above', 'below', 'behind', 'ahead', 'beside', 'between', 'among', 'within', 'without', 'inside', 'outside', 'nearby', 'far away', 'close by', 'otherwise', 'likewise', 'similarly', 'differently', 'specifically', 'particularly', 'especially', 'notably', 'remarkably', 'exceptionally') AND category LIKE 'general%';

-- تصنيف أدوات التعريف والنكرة
UPDATE words SET category = 'articles_determiners' WHERE word_en IN ('a', 'an', 'the', 'this', 'that', 'these', 'those', 'some', 'any', 'no', 'every', 'each', 'all', 'both', 'either', 'neither', 'few', 'little', 'many', 'much', 'several', 'enough', 'most', 'other', 'another', 'such', 'what', 'which', 'whose') AND category LIKE 'general%';